name = "irecommend-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

# routes = [
#   { pattern = "userreview.net", custom_domain = true },
#   { pattern = "www.userreview.net", custom_domain = true }
# ]


[vars]
R2_ENDPOINT = "https://25959c8efbcfc8ab377dd8d8d07df1de.r2.cloudflarestorage.com"
R2_BUCKET = "userreviewbudget"
R2_PUBLIC_BASE_URL = "https://images.userreview.net"
R2_REGION = "auto"
SUPABASE_URL = "https://gmpvaxfyawnqbdyyybbf.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtcHZheGZ5YXducWJkeXl5YmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzNDIzNjQsImV4cCI6MjA4MTkxODM2NH0.0bAXNixUdto8r0vXU89f8NFhQQqWIQV4DjghFqp3hEc"


[triggers]
crons = ["0 * * * *"]

